version: '3'
services:  
  scaffold:
    build:
      context: .
      dockerfile: docker/Dockerfile.scaffold
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    # command: /bin/bash -c "express"